#!/bin/bash

#set -x

# User can make a symbolic link to the app file
# In that case APP_PATH should be resolved and
# point to the original file, otherwise we would
# not be able to find all app libs and jars it
# depends on
APP_PATH=$(readlink "$0")
if [ $? -ne 0 ]; then
   APP_PATH="$0"
fi
APP_PATH=$(dirname "$APP_PATH")

# When started under cygwin or MSYS we need to 
# process classpath in the way that Java on Windows
# expects it
CP_SEP=":"
if [[ "$OS" =~ Windows ]]; then
    APP_PATH=$(cygpath -d "$APP_PATH")
    CP_SEP=";"
fi

# We cannot use -jar option because it ignores -cp and $CLASSPATH
java ${JAVA_ARGS} -cp "${APP_PATH}/libs/*" id.depresolve.app.Main "$@"
